### ISSUE TITLE
Only works with chef

### ISSUE THREAD

**Issue by hco** [etsy/nagios-herald#19]
From what I understand (and I don't understand ruby ;)) this currently kinda depends on chef, as https://github.com/etsy/nagios-herald/blob/master/lib/nagios-herald/helpers/ganglia_graph.rb#L1 includes some chef code.

This should be clarified in the documentation or changed.

Without chef being installed it results in the following:

```
3G icinga@icinga err: 130 ~ # /opt/nagios-herald/bin/nagios-herald  --help
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- chef/search/query (LoadError)
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /opt/nagios-herald/lib/nagios-herald/helpers/ganglia_graph.rb:1:in `<top (required)>'
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /opt/nagios-herald/lib/nagios-herald/helpers.rb:1:in `<top (required)>'
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /opt/nagios-herald/lib/nagios-herald.rb:7:in `<top (required)>'
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /opt/nagios-herald/bin/nagios-herald:3:in `<main>'
```

**Comment by nkammah** [comment]
@RyanFrantz I ran into similar issues whereby I did not install the chef gem (that requires ruby 2.0 btw which I did not want to muck on) - one of the commit in https://github.com/etsy/nagios-herald/pull/36 fixes the import issue, but not the underlying mechanism of the ganglia_graph helper. I also have not removed the dependency in the gemspec - I am not sure yet what would be the best approach to manage that gem since it could be an optional gem based on every user situation.
